# Generated by Django 2.1.3 on 2018-11-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='media/')),
                ('platform', models.CharField(choices=[('xbox', 'XBOX ONE'), ('playstation', 'Playstation 4'), ('Nintendo', 'Nintendo Switch'), ('PC', 'PC')], default='PC', max_length=30)),
            ],
        ),
    ]
