# Generated by Django 2.1.3 on 2018-12-07 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('buyer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('game', models.ManyToManyField(to='games.Game')),
            ],
        ),
    ]
